### ISSUE TITLE
Delete operation does not display a warning message

### ISSUE THREAD

**Issue by shankarkharel** [Des-Vu-Technologies/TodoApp#6]
I've noticed that the delete operation does not show a warning message or confirmation dialog when attempting to delete any item in the list. This omission can lead to accidental data loss and is not ideal from a user experience perspective.

**Comment by maheshwar04** [comment]
I will solve this issue assign this to me

**Comment by nabinkdl** [comment]
Issue Solved !!!

**Comment by shankarkharel** [comment]
closed
