### ISSUE TITLE
UI is so simple 

### ISSUE THREAD

**Issue by maheshwar04** [Des-Vu-Technologies/TodoApp#7]
As UI is so simple I want to change the UI of your todo website. If you allow, assign this issue to me .

**Comment by nabinkdl** [comment]
Okey maheshwar !!

**Comment by maheshwar04** [comment]
should i start contributing ?

**Comment by nabinkdl** [comment]
> should i start contributing ?
yes you can.🫡

**Comment by maheshwar04** [comment]
Ok
